### ISSUE TITLE
使用阿里云ECS结合Shadowsocks搭建自己的专属翻墙梯子 | 自律则自由

### ISSUE THREAD

**Issue by bozaigao** [bozaigao/BlogComments#5]
https://www.bozaigao.net/2019/11/07/%E4%BD%BF%E7%94%A8%E9%98%BF%E9%87%8C%E4%BA%91ECS%E7%BB%93%E5%90%88Shadowsocks%E6%90%AD%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84%E4%B8%93%E5%B1%9E%E7%BF%BB%E5%A2%99%E6%A2%AF%E5%AD%90/ 

 何晏波的个人博客，bozaigao's blog.

**Comment by bozaigao** [comment]
好

**Comment by Theodore-Ho** [comment]
ssserver -c /etc/shadowsocks.json -d start 启动之后，结果如下：

INFO: loading config from /etc/shadowsocks.json
2022-01-04 01:28:52 INFO     loading libcrypto from libcrypto.so.10
2022-01-04 01:28:52 INFO     loading libsodium from libsodium.so.23
started

客户端配置完成后无法连接。查看日志，结果如下：

2022-01-04 01:29:08 INFO     starting server at 我的IP地址:8888
Traceback (most recent call last):
  File "/usr/local/bin/ssserver", line 33, in <module>
    sys.exit(load_entry_point('shadowsocks==3.0.0', 'console_scripts', 'ssserver')())
  File "/usr/local/lib/python3.6/site-packages/shadowsocks/server.py", line 74, in main
    tcp_servers.append(tcprelay.TCPRelay(a_config, dns_resolver, False))
  File "/usr/local/lib/python3.6/site-packages/shadowsocks/tcprelay.py", line 754, in __init__
    server_socket.bind(sa)
OSError: [Errno 99] Cannot assign requested address

请问这个会是什么原因？

**Comment by jimmyfrank4855** [comment]
请问这种方法被查封的概率是多少，怎么有效地规避风险

**Comment by bozaigao** [comment]
@yushicheng 不稳定，我部署在香港的服务已经挂了，流量被过滤掉了，无法访问国外网站了，科学上网的话推荐使用第三方比如eVPN
